### PR TITLE
semicolons

### PR DESCRIPTION
**Pull request by juxd**
- fix typo
- add semicolon config
- add install hook for server

### CODE REVIEW

**Comment by juxd** [comment]
will need to think of a better way to install for both server and client. for now,

`cd server; yarn install-hook`

**Comment by juxd** [comment]
also this includes #2, if you merge this can close that one

**Review by pengnam — APPROVED** [review]

**Comment by pengnam** [comment]
@juxd I added the client side check. Help me do a quick pass? Typescript throws an error when I use React.FC<null> as the type of the components so some of the components definitions have an eslint-ignore to ignore that component type for now.

**Comment by pengnam** [comment]
Just merge whenever you are done w that

**Comment by pengnam** [comment]
Thank you for the PR!

**Review by juxd — COMMENTED** [review]
lgtm

**Pull request merged**
